Repository Comfy-Org/comfy-cli, pull requests merged in 2025-09, with the labels that each got.

#315 Add --no-deps to comfy node install.
  comfy_cli/command/custom_nodes/cm_cli_util.py
  comfy_cli/command/custom_nodes/command.py
  tests/comfy_cli/command/nodes/test_node_install.py
Labels: enhancement, size:L, lgtm

#316 fix node/npm/pnpm detection
  comfy_cli/command/install.py
Labels: bug, size:L

#319 Update install.py for Intel Arc GPUs
  comfy_cli/command/install.py
Labels: enhancement, size:S, lgtm

#320 Fix unnecessary full file download when checking URL authorization
  comfy_cli/file_utils.py
Labels: bug, size:XS, lgtm

#323 fix(CivitAI): correct parse URL with query params
  comfy_cli/command/models/models.py
  tests/comfy_cli/command/models/test_models.py
Labels: bug, size:L

#321 Add .comfyignore support to node packaging
  .gitignore
  DEV_README.md
  comfy_cli/command/custom_nodes/command.py
  comfy_cli/file_utils.py
  tests/comfy_cli/test_file_utils.py
  tests/test_file_utils_network.py
  tests/uv/test_uv.py
Labels: documentation, enhancement, size:L, lgtm
