Repository Comfy-Org/comfy-cli, pull requests merged in 2025-05, with the labels that each got.

#265 Fixed: Pin version of click dependency.
  pyproject.toml
Labels: dependencies, size:XS

#276 fix(config-parser): update registry domain into latest
  comfy_cli/registry/config_parser.py
Labels: size:XS, lgtm

#270 Added: publish all files in includes field in pyproject.toml
  comfy_cli/command/custom_nodes/command.py
  comfy_cli/file_utils.py
  comfy_cli/registry/config_parser.py
  comfy_cli/registry/types.py
  tests/comfy_cli/command/nodes/test_publish.py
Labels: enhancement, size:L, lgtm

#277 Fix Windows Unicode error in node commands
  comfy_cli/command/custom_nodes/cm_cli_util.py
Labels: bug, size:XS
