Repository Comfy-Org/comfy-cli, pull requests merged in 2025-08, with the labels that each got.

#286 feat: refactor env command to use ui.display_table for consistent table display
  comfy_cli/cmdline.py
  comfy_cli/config_manager.py
  comfy_cli/env_checker.py
  comfy_cli/workspace_manager.py
Labels: enhancement, size:M, lgtm

#298 fixed ruff; made it print in CI what needs to be changed
  .github/workflows/ruff_check.yml
  comfy_cli/cmdline.py
  comfy_cli/config_manager.py
  comfy_cli/env_checker.py
Labels: bug, size:M

#300 feat(codecov): added config
  .github/.codecov.yml
Labels: enhancement, size:S

#299 fix: use constants in ConfigManager
  comfy_cli/config_manager.py
Labels: bug, size:S, lgtm

#301 pre-commit: add pyproject-fmt
  .pre-commit-config.yaml
  pyproject.toml
  tests/uv/mock_comfy/custom_nodes/x/pyproject.toml
  tests/uv/mock_comfy/pyproject.toml
Labels: enhancement, size:M

#304 ruff: RET504 rule
  .github/codecov.yml
  .github/workflows/pytest.yml
  comfy_cli/command/models/models.py
  comfy_cli/command/run.py
  comfy_cli/file_utils.py
  comfy_cli/registry/api.py
  comfy_cli/workspace_manager.py
  pyproject.toml
Labels: size:M

#305 ci: add token permissions
  .github/codecov.yml
  .github/workflows/build-and-test.yml
  .github/workflows/publish_package.yml
  .github/workflows/pytest.yml
  .github/workflows/ruff_check.yml
  .github/workflows/run-on-gpu.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-windows.yml
Labels: size:S

#309 Add frontend PR support for testing ComfyUI_frontend pull requests
  README.md
  comfy_cli/cmdline.py
  comfy_cli/command/install.py
  comfy_cli/command/launch.py
  comfy_cli/command/pr_command.py
  comfy_cli/pr_cache.py
  tests/comfy_cli/command/github/test_pr.py
  tests/comfy_cli/command/test_frontend_pr.py
  tests/comfy_cli/command/test_launch_frontend_pr.py
Labels: enhancement, size:XL, lgtm

#308 add uv-pre-commit to handle dependency lock files
  .pre-commit-config.yaml
  pylock.toml
  uv.lock
Labels: enhancement, size:XS
